### ISSUE TITLE
obj.h doesn't work with Pelles C

### ISSUE THREAD

**Issue by altPOCA** [small-c/obj.h#3]
I'm testing win32_app with Pelles C. It failed to compile with a bunch of errors I don't understand. Perhaps you should download Pelles C and playing a bit with it.

**Comment by nomi-san** [comment]
Does other examples work with Pelles C?

**Comment by altPOCA** [comment]
None of the examples work. The errors reported are in obj.h itself. There are too many errors so I suggest you install Pelles C to have the first hand experience. If you said you have no time for Pelles C please dismiss this report. Since even if I posted the errors (too many), you can't fix them unless you also use Pelles C.
