### ISSUE TITLE
Support Pelles C

### ISSUE THREAD

**Issue by ghost** [small-c/obj.h#5]
Pelles C is Windows only. Able to generate both 32 bit and 64 bit binaries. Why Pelles C? Pelles C is small and lightweight. MSVC and mingw64 are beasts, eating gigabytes of precious disk space. Oh almost forgot, this is Pelles C: http://www.smorgasbordet.com/pellesc/

**Comment by nomi-san** [comment]
I tried both C99 and C11 standard, but there was no difference.
Seems Pelles C compiler does not support implicit pointer cast.
Here is the foo.c compilation output.

![image](https://user-images.githubusercontent.com/38210249/187820498-7c4a0f63-17fd-4ee0-9160-936bcebb46a4.png)

**Comment by ghost** [comment]
> I tried both C99 and C11 standard, but there was no difference. Seems Pelles C compiler does not support implicit pointer cast. Here is the foo.c compilation output.
> 
> ![image](https://user-images.githubusercontent.com/38210249/187820498-7c4a0f63-17fd-4ee0-9160-936bcebb46a4.png)

Regarding these low level details, better just reach out to Pelles C developer. He is on Pelles C forum: https://forum.pellesc.de/

**Comment by ghost** [comment]
Duplicated of https://github.com/small-c/obj.h/issues/3
