### ISSUE TITLE
How is it compared to OCC?

### ISSUE THREAD

**Issue by 3oheicrw** [small-c/obj.h#7]
https://ooc-coding.sourceforge.net/

**Comment by nomi-san** [comment]
Look at this OOC example:
```c
Desktop	desktop;
ooc_init_class( Exception );

desktop = desktop_new();
{
  ooc_manage_object( desktop );
  ooc_get_interface_must_have( desktop, Serializable )->serialize( (Object) desktop, 0 );
  ooc_delete( (Object) ooc_pass( desktop ) );
}

ooc_finalize_all();
```

Our `obj.h` can do better:
```c
Desktop desktop = new(Desktop)();
desktop->serialize(0);
desktop->bease.release();
```

Our library is just a single header, it provides standard C++/Java OOP like, and keeps focus on..
```c
self->method(/* without self here */);
```

**Comment by 3oheicrw** [comment]
OCC seems to be plain C, obj.h is an assembly hack isn't it? Because of that, OCC will always work but obj.h could possibly break with future versions of GCC?

**Comment by nomi-san** [comment]
Maybe, but it mainly depends on CPU architecture.
Back to GCC 4.0 (2005), it works correctly, and up to current version.

The CPU instructions seems never change, even though new modern CPU releases.
But this library must implement for new CPU arch, e.g ARM64, see #4.

**Comment by 3oheicrw** [comment]
> Maybe, but it mainly depends on CPU architecture. Back to GCC 4.0 (2005), it works correctly, and up to current version.
> 
> The CPU instructions seem never change, even though new modern CPU releases. But this library must implement for new CPU arch, e.g ARM64, see #4.

Final question, how obj.h compared to these?

https://github.com/CObjectSystem/COS

https://github.com/GorgonMeducer/PLOOC

**Comment by nomi-san** [comment]
The popular OO implementation in pure C is around this concept:
```c
typedef struct _object Object;

struct _object {
  void (*method)(Object *);
  void (*anotherMethod)(Object *, int);
};

void _object_method(Object *this) {
  this->anotherMethod(this, 100);
}

Object obj = /* create an instance */;
obj->method(obj);
```

The strong points of obj.h is compared to others are:
- Sweet syntax: similar to C++, code shorter, no need to put `this` as the first param.
- Single header: only one .h file and zero dependency.

**Comment by 3oheicrw** [comment]
Thank you.
